#!/bin/zsh

#  Cryptography
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Open URL
function frequency_analysis() {
    local url="http://www.richkni.co.uk/php/crypta/freq.php"
    print "${CYAN}${url}${NORMAL}"
    open -b 'com.apple.Safari' $url
}
