#!/bin/zsh

#  Cryptography
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function fromto() {
    from=$(letter $1)
    to=$(letter $2)
    dist=$(( $to - $from ))
    print -c "Distance from $from to $to: ${CYAN}${dist}${NORMAL}"
}
