#!/bin/zsh

#  Cryptography
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Print keys used to encrypt and decrypt a message
function key_pair_caesar() {
    local d_key=${1? Decryption key not set}
    local e_key=$(( d_key - 26 ))
    echo "If ${CYAN}decryption${NORMAL} key is ${CYAN}k=${d_key}${NORMAL}, then message"
    echo "was ${GREEN}encrypted${NORMAL} with ${GREEN}k=${e_key#-}${NORMAL}"
}
