#!/bin/zsh

#  Cryptography
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function letter() {
    alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    L=${1:u}
    for i in {0..25}; do
        pos=$(( $i + 1 ))
        if [[ $L == $alphabet[$pos] ]]; then
#            print $i
            print -c "${CYAN}${L}=${i}${NORMAL}"
            return 0
        fi
    done
    
    echo "Err"
    return 1
}
