#!/bin/zsh

#  Cryptography
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function math() {
    local args=$@
    r=$(( $@ ))
    
    $(printable) &&
        print "${args} = $( c $(math $@) )" ||
        print "$r"
}
