#!/bin/zsh

#  Read help
#  Documents & Support
#
#  Created by mpuchkov on 2020-02-01.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


autoload +X chelp

CHELP_ROOT_DIR="$xct/chelp_pages"
CHELP_LISTS=( "$CHELP_ROOT_DIR/networking" )

export CHELP_ROOT_DIR
export -a CHELP_LISTS


function chelp() {
    


    # List all functions
    function chelp_lists() {
        print_h "Help Lists"
        echo "${(F)CHELP_LISTS:t}"
    }
    
    function chelp_pages() {
        SYNTAX="chelp pages in_list]"
        local list=$1
        if [[ -z $list ]]; then
            serror "in_list" $SYNTAX
        fi
        print_h "Help Pages in $list"
        echo
    }
    
    function chelp_get() {
        local page=$1
        for list in $CHELP_LISTS; do
            local pagefile=$list/$page
            if [[ -r $pagefile ]]; then
                print_h "Help page for '${pagefile:t}'" 1 'cyan'
                highlight -l -z --SYNTAX=txt $pagefile
                return 0
            fi
        done
        error "help page not found."
    }
    

    SRC=$(basename $0)
    subcommand=$1
    case $subcommand in
        "")
            print "Usage:"
            print -x2 "\t$(Bc 'doc') $(Uc 'name'): open documentation."
            print -x2 "\t$(Bc 'doc') $(c 'list'): view available help lists."
            ;;
        *)
            shift
            ${SRC}_${subcommand} $@
            s=$?
            if [ $s = 127 ]; then
                echo "Unknown command: $(r $subcommand) ($s)." >&2
            fi
            ;;
    esac
    
}


chelp $@
