#!/bin/zsh


function compl() {
    
    ## fn0: this function does not match ##
    function non_matching_compl_fn0() {
        echo 'ERR'
        return 1
    }

    ## fn1: print 1 ##
    function compl_fn1() {
        echo '1'
        return 0
    }
    ## fn2: print 2 ##
    function compl_fn2 () {
        echo '2'
        return 0
    }
    ## fn3: print 3 ##
    function compl_fn3() { echo '3'; return 0; }
    
    
    function compl_fn4() {
        echo 'no tooltip'
        return 0
    }
    
    ## fn4: ? ##
    function compl_fn5() {
        echo 'not fn4'
        return 0
    }
    
}
