#!/bin/zsh

#  hints
#  Documents & Support
#
#  Created by mpuchkov on 2020-02-23.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function hint() {

    function desc() {
        local cmd_name="$(U $(Bc ${1#hint_}))"
        local cmd_desc="$(blue $2)"
        echo "$cmd_name: $cmd_desc"
    }

    function hint_freq() {
        desc "$0" "Some text"
        history | awk '{print $2}' | sort | uniq -c | sort -rn | head
    }
    
    
    
    hint_freq

}
