#!/bin/zsh

#  snip
#  Documents & Support
#
#  Created by mpuchkov on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function snip() {


function snip_opts() {
    cyan 'Save options to array:'
    cat <<-'EOF'
        typeset -A opts
        set -A opts $( read_options "$@" )
        shift $( options_shift_distance "$@" )
EOF
}
function snip_silent() {
    cyan 'Suppress standard output and error messages:'
    cat <<-'EOF'
        cd 'not-dir'                # Message: no such file or directory. Code: 1.
        cd 'not-dir' >& /dev/null   # No message. Code: 1.
EOF
}

    src=$(basename $0)
    cmd=$1
    case $cmd in
        "")
            print "Usage:"
            print -x2 "\t$(Bc 'snip') $(Uc 'snippet_name'): print code snippet."
            ;;
        *)
            shift
            ${src}_${cmd} "$@"
            local ecode=$?
            if [ $ecode = 127 ]; then
                echo "Unknown command: $(r $cmd) (Exit code $ecode)." >&2
            fi
            ;;
    esac
    
}
