#!/usr/local/bin/python3

#  PYTHONSTARTUP
#
#  Python commands in this file are
#  executed before the first prompt
#  is displayed in interactive mode.
#
#
#  Created on August 12, 2020.


# Link this file to home diretory:
#   `/bin/ln -s /usr/local/Terminal/etc/python/pythonstartup ~/.pythonstartup'



## Not included
# from rsa import *
# from hexio import *
# from CG import *
# from MISC import *
# from SIGN import *
# from Cryptodome.Util.number import getPrime, isPrime, inverse
# import random
# from cfin import *
# from SETS import *


