#!/bin/zsh

#  Identity
#  com.maximpuchkov.services.Identity
#
#  Created by Maxim Puchkov on 2020-05-26.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


#
log_prefix="$(date -r $current_time -j +'%b %d %T') $(hostname -s) ${0:t}[$$]:\t"

echo "${log_prefix} [0] OK."
echo "${log_prefix} [1] Error." >&2



exit 0
