#!/bin/zsh


alias set='()
set() {
  
  builtin set $argv
}

return 0


#function find() {
typeset -a reply
reply=$(/usr/bin/find $argv)

local file
for file in $reply; do
  if [[ -L $file ]]; then
    print
  fi
  print File is $file
done







#}
#
#(
#  while [[ -n $1 ]] && [[ ! $1 =~ '^[-]' ]]; do
#  if [[ -L $1 ]]; then
#    echo "Directory $1 is a symlink"
#  fi
#  shift
#  done
#)
#
#find $@
