#!/bin/zsh

#  confirm
#
#
#  Created by mpuchkov on 2020-01-30.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Display a confirmation prompt and wait for response.
# If response is affirmative: do nothing;
#                  otherwise: interrupt the calling function.
function confirm() {
    # Confirmation message and default action.
    local message_label="${1:-Are you sure you want to continue?}"
    local default_action="${2:-no}"
    
    # Actions' text style.
    local action_y=$(b_green 'yes')
    local action_n=$(b_red 'no')
    local actions=($action_y $action_n)
    local actions_label=${(j:/:)${actions/${default_action}/$(U ${default_action})}}
    
    # Show message and wait for input.
    print -n "${message_label} ${actions_label} "
    read response
    
    # Interrupt if the response was not affirmative.
    setopt nocasematch
    if [[ ! $response =~ '^y(es)?$' ]]; then
        signal interrupt
    fi
}
