#!/bin/zsh

#  get_options_v2
#  Z-Function
#
#  Created by admin on 2020-04-15.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.
 

# Read all command options and store in an array with
# the specified identifier.
#   get_options identifier options...
function get_options_v2() {
    local identifier=$1
    local optstring="$2"
    local arguments=${@:3}
    
    SYNTAX="$0 identifier optstring arguments"
    syntax_check "$SYNTAX" ||
        return 1
    
    typeset -A result
    local opt=''
    local length=0
    while getopts "$optstring" opt ${(z)arguments[@]} 2> /dev/null ; do
        if [[ $opt == '?' ]]; then
            length=$(( $length + 1 ))
            continue;
        fi
        if [[ -n $OPTARG ]]; then
            result[$opt]=$OPTARG
            length=$(( $length + 2 ))
        else
            result[$opt]='true'
            length=$(( $length + 1 ))
        fi
    done
    
    arg_list=(${(z)arguments})
    result[length]=$length
    result[command_arguments]=${(qq)${arg_list:$length}:-''}
    
    typeset -Ag $identifier
    set -A $identifier ${(kv)result}
    return 0
}



#MARK: - Examples
# Example:
#   typeset -A command_options
#   command_input=(--ox 0 --oy 100 --3d --color=red)
#   get_options command_options $command_input
#   shift $command_options[shift_distance]

# Result:
#   Arr[ox]=0, Arr[oy]=100, Arr[3d]=set, Arr[color]=red.
