#!/bin/zsh

#  get_options
#  devx
#
#  Created by admin on 2020-03-06.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.
 

# Read all command options and store in an array with
# the specified identifier.
#   get_options identifier options...
function get_options2() {
    local identifier=$1
    local optstring="$2"
    shift 2
    local arguments="$@"
    
    SYNTAX="$0 identifier optstring arguments"
    syntax_check "$SYNTAX"
#    serrif "-z $identifier" "-z $optstring arguments" $SYNTAX
    
    typeset -A result
    local opt=''
    while getopts "$optstring" opt ${(z)arguments[@]}; do
        echo "Option: $opt | Argument: $OPTARG"
        result[$opt]=${OPTARG:-true}
    done
    
    typeset -Ag $identifier
    set -A $identifier ${(kv)result}
    return 0
}



#MARK: - Examples
# Example:
#   typeset -A command_options
#   command_input=(--ox 0 --oy 100 --3d --color=red)
#   get_options command_options $command_input
#   shift $command_options[shift_distance]

# Result:
#   Arr[ox]=0, Arr[oy]=100, Arr[3d]=set, Arr[color]=red.
