#!/bin/zsh

#  grepman
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-08.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Search manual pages for lines matching the pattern.
function grepman() {
    local manpage=$1
    local pattern=$2
    # Display error if manual page not specified
    SYNTAX="$0 manpage pattern?"
    if (! syntax_check "$SYNTAX"); then return 1; fi
    # Print matching lines
    local contents=$( man $manpage | colcrt - )
    printf '%s\n' "$contents" | grep -a -i --color -e "${pattern}"
}
