#!/bin/zsh

#  grepman
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-08.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Search manual pages for lines matching the pattern.
function grepman() {
    SYNTAX=(grepman manual_page pattern)
    local manpage=$1
    local pattern=$2
    # Display error if manual page not specified
    if [[ -z $manpage ]]; then
        serror 'manual_page' "$SYNTAX"
        return 1
    fi
    # Print matching lines
    local contents=$( man $manpage | colcrt - )
    echo "$contents" | grep -a -i -e "${pattern}" --color
}
