#!/bin/zsh

#  helpme
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-21.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function helpme() {
    printf 'Template z-function: %s.\n' $(blue "$0")
    
    # Print to stderr
    local def=$(fn src $0)
    if [[ $? -ne 0 ]]; then
        printf 'Definition not found.\n' >&2
        return 1
    fi
    
    printf 'Defined in: %s.\n' $(blue "$def")
#    printf '%s\n' ${"$(fn body $0)"}
    return 0
}
