#!/bin/zsh

#  isdef
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-24.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function isdef() {
    local var_id=${(j:_:)@}
    if [[ ${+functions[$var_id]} -eq 0 ]]; then
        return 1
    fi
    return 0
}
