#!/bin/sh

#  mantxt.sh
#  devx
#
#  Created by admin on 2020-03-12.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Display full manual page as text or
# search for matching pattern.
function mantxt() {
    local manpage=$1
    local search=(${@:2})
    
    local contents=$( man $manpage | colcrt - )
    if [[ ${#search} -eq 0 ]]; then
        echo "$contents"
    else
        echo "$contents" | grep -a --color $search
    fi
}
