#!/bin/zsh

#  newcomm
#  devx
#
#  Created by admin on 2020-03-04.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Search and Display History
function newcomm() {
    local manager=$1
    local p
    case $manager in
        'brew')     p='brew install'      ;;
        'port')     p='sudo port install' ;;
             *)     Warn 'Package manager is not specified.'
                    printf '%s\n' "Showing new 'brew' commands."
                    p='brew install'      ;;
    esac
    local sed_p="^.*${p}[[:space:]]+"
    local replace_with="    "
    local grep_p="^.*\s+${p}\s.+"

    printf '%s: omz_history | grep -i -E "%s" | sed -E "s/%s/%s/"\n' "$(red 'Command')" "$grep_p" "$sed_p" "$replace_with"
    omz_history | grep -i -E "$grep_p" | sed -E "s/$sed_p/$replace_with/"
}
