#!/bin/zsh

#  pack
#  devx
#
#  Created by mpuchkov on 2020-03-04.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Create new empty subdirectory 'subdir'. Move all
# files in the parent directory 'dir' to 'dir/subdir'.
function pack() {
    if [[ -z $1 || -z $2 ]]; then
        return 1
    fi
    
    local dir=${1:a}
    local subdir=$dir/$2
    local files=($dir/*)
    mkdir -p $subdir
    for f in $files; do
        echo $f
    done
    yellow "dir=$(countf . $dir)"
    yellow "sub=$(countf . $subdir)"
}
