#!/bin/zsh

#  save_array
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-08.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Save array to file.
function save_array() {
    local identifier="$1"
    if [[ ! ${(t)${(P)identifier}} =~ 'array' ]]; then
        Bad 'not an array' ${(t)${(P)identifier}}
        return 1
    fi
    local file="$DEV/Library/Data/$identifier.array"
    print -r -- ${(qq)${(P)identifier}} > $file
}
