#!/bin/zsh

#  search
#  devx
#
#  Created by admin on 2020-03-03.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


#
function search() {
    function search_pattern() {
        local pattern="$1"
        local text="$2"
        if [[ -z $text ]]; then
            text=$(< /dev/stdin)
        fi
        echo "$text" | grep -i -E "$pattern" --color
    }
    
    # Function options.
    typeset -A opts
    set -A opts $( read_options "$@" )
    shift $( options_shift_distance "$@" )
    
    # Source and compound commands.
    src=$( basename $0 )
    cmd=$1
    
    # Compound command.
    case $cmd in
        "")
            print "Usage:"
            print -x2 "\t$(Bc $src) $(c 'pattern') $(Uc 'text') - search for 'pattern' in 'text'."
            ;;
        *)
            shift
            ${src}_${cmd} "$@"
            local ecode=$?
            if [ $ecode = 127 ]; then
                echo "Unknown command: $(r $cmd) (Exit code $ecode)." >&2
            fi
            ;;
    esac
}

