#!/bin/sh

#  synopsis
#  devx
#
#  Created by admin on 2020-03-11.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Syntax (sx)
#   Display name, synopsis, and brief description (first
#   paragraph) of a command, function, or file.
function syntax() {
    export SYNTAX=(syntax name)
    local manpage=$1
    
    # Search manual page.
    function pattern_search() {
        local text=$1
        local pattern=$2
        local result=($( echo "$text" | grep -a -i -E "$pattern" -A 1 ))
        echo "${result[@]:1}"
    }
    # Display section title and text.
    function display() {
        local title=$1
        local text=$2
        local highlight_manpage=$( bmagenta $manpage )
        local highlight_text=${text//$manpage/$highlight_manpage}
        InfoSection "$title"
        echo "$highlight_text"
    }
    
    
    # Check arguments.
    if [[ -z $manpage ]]; then
        serror 'name' "$SYNTAX"
    fi
    
    # Check that manual page exists.
    man $manpage >& /dev/null
    if [[ $status -ne 0 ]]; then
        error "Manual page for $(Bad $manpage) not found."
    fi
    
    # Get name, synopsis, and description from manual page contents.
    local contents=$( mantxt $manpage )
    local name=$( pattern_search $contents '^NAME$' )
    local synopsis=$( pattern_search $contents '^SYNOPSIS$' )
    local desc=$( brief $manpage )
    
    # Display with section titles.
    display "Name"        "$name";     echo;
    display "Synopsis"    "$synopsis"; echo;
    display "Description" "$desc";
    
    return 0
}
