#!/bin/zsh

#  test-ref
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-21.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function test-ref() {
    printf 'Template z-function: %s.\n' $(blue "$0")
    
    # Print to stderr
    local def=$(fn src $0)
    if [[ $? -ne 0 ]]; then
        printf 'Definition not found.\n' >&2
        return 1
    fi
    
    printf 'Defined in: %s.\n' $(blue "$def")
    return 0
}

# modf:
#   26610
#   10981
#   13489
#   2706
#   17750
