#!/bin/zsh

#  zfc_completion
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


## completion: autogenerate function completion ##
function zfc_completion() (
    local fn_name="$1"
    if [[ -z $fn_name ]]; then
        return 1
    fi
    
    typeset -A reply
    typeset -a fn_commands
    local fn_files=($( find "$zfunc/zshell" -regex "$zfunc/zshell/$fn_name.*" ))
    
    for fn_file in $fn_files; do
        local fn=${fn_file:t}
        autoload +X $fn
        fn_commands=($( fn -p "$fn" commands ${fn} ))
        for cmd in $fn_commands; do
            local pattern="## ${cmd}: .+ ##.*function ${fn_name}_${cmd}[\s]*\(\)"
            local description=$(
                greps '-o' "$pattern" "$fn_file" |
                    head -n 1 |
                    sed -e "s/## ${cmd}: //g" -e "s/ ##.*//g"
            )
            reply[$cmd]="${description:-''}"
        done
    done
    
#    print-association reply
#    echo ${(kv)reply}
    
    cat <<- EOF
#compdef $fn_name

_arguments -C \\
  '-h[display help]:file:_files' \\
  '(-h):command:->command' &&
    ret=0

case \$state in
  command)
    declare -a commands
    commands=(
$( for k v in ${(kv)reply}; do
  printf "      %s:\"%s\" \\ \n" "$k" "$v" | colrm;
done )
    )
    _describe -t commands command commands &&
      ret=0
    ;;
esac
EOF
)
