#!/bin/zsh

#  zfunction-show
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-18.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function zfunction-show() {
    typeset -ag list
    
    list=() #( 'Z-Function' 'Date Modified' )
    local dir="$zfunc/zshell"
    for file in $dir/*; do
        local mod_date="$(stat -f '%m' $file)"
        list+=( "${(q)file##*'/'}" "${(q)mod_date}" )
    done
    
    
    local recent=$( printf '%s %s\n' $list | sort -k2n | tail -1 | awk '{print $1}' )
    
    
    function format_date() {
        printf '%s\n' "$( date -r $1 -j +'%b-%d-%Y %R' )"
    }
    
    
    # Options
    local show_lines=${#list:2}
    local sort_options='--key 2n'
    if [[ $# -gt 0 ]]; then
        local count=$1
        if [[ $count -gt 0 ]]; then
            sort_options='--key 2nr'
        else
            count=$(( $count * -1 ))
        fi
        show_lines=$count
    fi
    
    
    # Table
    local -a table_header=()
    local table_div=''
    local div_length=0
    typeset -ag table_body=()
    local div_length=''
    
    
    # Header
    local column1_header='FUNCTION' #"$(bold 'Z-Function')"
    local column2_header='DATE MODIFIED' # "$(bold 'Date')"
    table_header=(
        "$( printf '%s\t\t%s' "$column1_header" "$column2_header" |
                expand -t 8 )"
    )
    
    
    # Divider
    longest_row=(
        $( printf '%s %s\n' $list |
            awk '{print length, $1, $2}' |
            sort |
            tail -1 )
    )
    div_length=$(
        printf '%s %s\n' $longest_row[2] $(format_date $longest_row[3]) |
            column -t |
            wc -c
    )
    table_div=$(
        printf '%-*s\n' ${div_length} '' |
            tr ' ' '-'
    )
    
    
    # Table body
    function generate_table() {
        printf '%s %s\n' ${(@)list} |
            sort ${(z)sort_options} |
            while read fn_name fn_mod_date; do
                local formatted_name="$(blue $fn_name)"
                local formatted_date="$(date -r $fn_mod_date -j +'%b-%d-%Y %R')"
                printf '%s %s' $formatted_name $formatted_date

                if [[ $fn_name == $recent ]]; then
                    printf '\t (%s)' "$(green 'most recent')"
                fi
                printf '\n'
            done |
            column -t |
            head -n $show_lines
    }
    table_body="$( generate_table )"
    
    
    # Print table
    printf '%s\n' "$table_header"
    printf '%s\n' "$table_div"
    printf '%s\n'   "$table_body"
    
#    printf '%s %s\n' ${table_body}
#    printf '\t(%s)\n'  #


    return 0
}
