#!/bin/zsh

#  0b
#  Z-Function (99)
#
#  Created by Maxim Puchkov on 2020-07-14.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Convert ASCII to binary
function 0b() {
  # Get ASCII from standard input or
  # positional parameters
  typeset ascii
  if zselect -t 0 -r 0; then
    ascii=${(@f)"$(<&0)"}
  else
    ascii=${argv}
  fi
  # Stop if input string is empty
  [[ -z $ascii ]] && return 1
  
  
  # Convert input to binary
  typeset hex=$(0x $argv)
  typeset -i2 binary
  let binary="[##2]${hex}"
  builtin print -- "$(( [##2] ${binary} ))"
  return 0
}
