#!/bin/zsh

#  app
#  Z-Function (16)
#
#  Created by Maxim Puchkov on 2020-05-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function app() {
    local app_name="$1"
    local flags=('')
    
    ## finder: open Finder ##
    function app_finder() {
        open $flags -a Finder
    }
    ## safari: open Safari ##
    function app_safari() {
        open $flags -a Safari
    }
    ## xcode: open Xcode ##
    function app_xcode() { open $flags -a Xcode; }
    
    # Execute the command
    local cmd=$1
    ${0}_${cmd} $fname
    return $?

}
#    find ~/Applications /Applications /System/Applications -maxdepth 2 -mindepth 1 -iregex ".*$n.*\.app"}
