#!/bin/zsh

#  arrays
#  Z-Function (44)
#
#  Created by Maxim Puchkov on 2020-05-30.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function arrays() {
    
    function arrays-only() {
        typeset filter="$1"
        typeset -a matching=(${(M)array_data:#$~filter})
        typeset -i match_size=${#matching}
        print -P -- "%F{2}${match_size}%f of ${array_size} elements %F{2}match%f pattern %U$filter%u."
        print -P -l -- ${matching:-'No matches'}
    }
    
    function arrays-except() {
        typeset filter="$1"
        typeset -a matching=(${(M)array_data:#$~filter})
        typeset -i match_size=${#matching}
        if [[ $match_size -eq 0 ]]; then
            print 'No matches.'
        print -P -- "%F{2}${match_size}%f of ${array_size} elements %F{1}do not match%f pattern %U$filter%u."
        print -P -l -- ${matching:-'No matches'}
    }
    
    
    typeset cmd=$1
    shift
    typeset    array_id=$1
    typeset -a array_data=(${(P)array_id})
    typeset -i array_size=${#array_data}
    shift
    
    ${0}-${cmd} "$@"
}
