#!/bin/zsh

#  caller
#  Z-Function (85)
#
#  Created by Maxim Puchkov on 2020-07-05.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function caller() {
    if [[ $# -ne 0 ]]; then
      error -1
    fi
        
    typeset caller_id=${funcstack[3]:-$SHELL}
      show $caller_id
    
    typeset fn=$1
    () (
        functions[$fn]="caller; $functions[$fn]"
        functions $fn
        $fn
    )
    
}
