#!/bin/zsh

#  cats
#  Z-Function (90)
#
#  Created by Maxim Puchkov on 2020-07-08.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function cats() {
  local input
  local file
  for file; do
    printf 'File: %s\n' "$(bold $file)"
    cat <$file
    
    if [[ $file == ${argv[-1]} ]]; then
      break
    fi
    
    yellow $(em 'Press return to continue...')
    read -sk input
    
    if [[ $input != $'\n' ]]; then
      break
    fi
  done
}
