#!/bin/zsh

#  commands
#  Z-Function (36)
#
#  Created by Maxim Puchkov on 2020-05-19.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function commands() {
    typeset pattern=$1
    () (
        PCREGREP_COLOUR='01;96'
        pcre2grep --color='always' --regexp "$pattern" $1
    ) =( print -l ${commands:t} )
}
