#!/bin/zsh

#  convert
#  Z-Function (19)
#
#  Created by Maxim Puchkov on 2020-05-04.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Convert from one unit to another.
function convert() {
    if [[ $# -lt 3 ]]; then
        error 'Not enough arguments.\nUsage:' \
              '1) convert 42 meters inches.' \
              '2) myVar=42;  convert --var myVar km cm.'
        return 2
    fi
    typeset -A optlist
    typeset -a args
    args=( $argv )
    get-options optlist args
    
    local ov cv from_unit to_unit
    case $optlist[var] in
        '') ov=$1
            out=(printf '%s\n')
        ;;
         *) ov=${(P)optlist[var]:-1}
            out=(set -A $optlist[var])
            shift
        ;;
    esac
    
    if [[ $ov -gt 0 ]]; then
        from_unit=$2
        to_unit=$3
        cv=($( units -- "$ov $from_unit" "$to_unit" ))
    else
        cv=0
    fi
    
    $out $cv[2]
    return 0
}
