#!/bin/zsh

#  corrupt
#  Z-Function (108)
#
#  Created by Maxim Puchkov on 2020-07-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# corrupt - corrupt a single bit in a file
function corrupt() {
  # Require path to input file
  if [[ $# -lt 1 ]]; then
    usage 'Input file is not specified.' - \
          'corrupt input_file [output_file]'
    return 1
  fi
  
  
  # Input file path
  typeset input_file=$1
  if [[ ! -e $input_file ]]; then
    error -1 'Input file does not exist: ${input_file}.'
    return 1
  fi
  # Output file path
  typeset output_file=$2
  if [[ -z $output_file ]]; then
    output_file="${input_file:r}~corrupt.${input_file:e}"
  fi
  if [[ -e $output_file ]]; then
    error -1 'Output file already exists: ${output_file}.'
    return 1
  fi
  
  
  # 
  typeset binary=$(0b <$input_file)
  printf '%s\n' "$binary"
}
