#!/bin/zsh

#  crontab-generate
#
#
#  Created by Maxim Puchkov on 2020-04-16.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function crontab-generate() {
    open -a Safari 'https://crontab-generator.org'    
}
