#!/bin/zsh

#  files
#  devx
#
#  Created by admin on 2020-03-10.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Count matching files in a directory.
function files() {
    #
    function files_count() {
        local in_dir="${${1:-.}:a}"
        local filename="$2"
        if [[ ! -e "$in_dir" ]]; then
            error "Directory not found: $in_dir."
            return 1
        fi
        cd "$in_dir"
        local regex="^\.\/${filename}[[:alnum:]_\.\-]*"
        echo $( find . ! -name . -prune -print | grep -i -E "$regex" -c )
        cd "$OLDPWD"
    }
    
    # 
    function files_find() {
        local filename=$1
        local found=$( find . \
            -iname $filename  \
            -mindepth 1       \
            -maxdepth 1       \
            -and \( -type f -or -type l \) \
            2>/dev/null )
        if [[ -z $found ]]; then
            return 1
        fi
        printf '%s\n' "$found"
        return 0
    }
    
    if [[ $# -eq 0 ]]; then
        fn print-commands $0
        return 2
    fi
    
    if [[ $# -eq 1 ]] && ( ! fn isdef ${0}_${1} ); then
        files find $1
        return $?
    fi
    
    local cmd=$1
    shift
    ${0}_${cmd} "$@"
    return $?
}
