#!/bin/zsh

#  finclude
#  Z-Function
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function finclude() {
    autoload -z fload
    fload
}

#finclude
