#!/bin/zsh

#  fs
#  Z-Function (5)
#
#  Created by Maxim Puchkov on 2020-04-27.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Find strings in files
function fs() {
    if [[ $# -eq 0 ]] return 2
    
    local string="$1"
    local search_directory="${${2:-.}:a}"
    local depth="${3:+-maxdepth $3}"
    
    local files=($( find $search_directory -type f ${(z)depth} ))
    local n_files=${#files}
    local n_matches=0
    
    for f in $files; do
        local match=$( grep --color='always' -i -E "$string" -- "$f" )
        if [[ -n $match ]]; then
            n_matches=$(( $n_matches + 1 ))
            printf "$(bluebg '[%d] %s')\n" $n_matches "$f"
            printf '%s\n\n' $match
        fi
    done
    
    printf "Found $(blue '%d') matches in $(blue '%d') files.\n" $n_matches $n_files
    
    return 0
}
