#!/bin/zsh

#  fsize
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-25.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Print file size in bytes
function fsize() {
    # Supress error messages
    local quiet=0
    local stdout=/dev/stdout
    local stderr=/dev/stderr
    if [[ "$1" == '-q' ]]; then
        quiet=1
        stderr=/dev/null
        shift
    fi

    local name type sizeunit tmp
    for file in ${${@:-*}:a}; do
        float size=0
        sizeunit='KB'
        type=$(stat -f '%HT' $file)
        printf '%s: ' "$file"
        case $type in
            'Regular File')
                stat -f '%z %N' $file |
                read -r {size,name}
                convert --var size 'byte' 'kilobyte'
            ;;
            
            'Directory')
                du -k -d0 $file 2>/dev/null |
                read -r {size,name}
            ;;
            
            *)
                continue
            ;;
        esac
        
        if [[ $size -ge 1048576 ]]; then
            convert --var size 'kilobyte' 'gigabyte'
            sizeunit="GB"
        elif [[ $size -ge 1024 ]]; then
            convert --var size 'kilobyte' 'megabyte'
            sizeunit="MB"
        fi
        printf "${fg[blue]}%.2f %+2s${fg[default]}\n" "$size" "$sizeunit"
    done
    
    return 0
}
