#!/bin/zsh

#  fstr
#  Z-Function (5)
#
#  Created by Maxim Puchkov on 2020-04-27.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Find strings (or patterns) in files.
function fstr() {
#    if [[ $# -eq 0 ]] return 2
    
    if [[ $# -eq 0 ]]; then
        error -2 'No input.\nUsage: %B%Ufstr%u <directory> <string>%b.'
    fi
    
    # String, directory, and depth
    local search_directory="${${1:-.}:a}"
    local string="${2:-.}"
    
    # Files in the directory
    typeset -a files=(${(@f)"$(
        find $search_directory -type f
    )"})
    typeset -i10 n_files n_matches
    n_files=${#files}
    n_matches=0
    
    # Find matching files
    local file match
    for file in $files; do
        match=$( colorize_grep 'b_byellow' \
            egrep --color='always'       \
                  --ignore-case          \
                  --text                 \
                  --regexp "$string" --  \
                  $file )
        if [[ -n "$match" ]]; then
            n_matches=$(( $n_matches + 1 ))
            print -P -- "%B%K{11}%F{16} [$n_matches]  $file %f%k%b"
            print    -- "$match\n"
        fi
    done
    
    # Display number of matches and files
    print -P -- "$n_matches out of $n_files files match."
    return 0
}
