#!/bin/zsh

#  greps
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-14.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Search files for the specified multi-line
# pattern in one or many files.
function greps() {
    # pcregrep otpions, the pattern, and files
    local opts=$1
    local pattern="$2"
    local filepaths=("${@:3}")
    
    # Check command syntax
    SYNTAX="$0 opts? pattern filepaths+"
    if (! syntax_check "$SYNTAX"); then return 1; fi
    
    # Search every file
    for filepath in $filepaths; do
        pcregrep ${(z)opts} \
            --color='auto' \
            --multiline \
            --newline='CR' \
            --regex "$pattern" \
            < "$filepath"
    done
    return 0
}
