#!/bin/zsh

#  i
#  Z-Function (30)
#
#  Created by Maxim Puchkov on 2020-05-07.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function i() {
    typeset -A optlist
    typeset -a args=($argv)
    get-options -f 'v' optlist args
    

    
    local name info
    name="$args"
    info=(${(@f)"$(whence -av $name)"})
    
    local print_autoload_function='print -P %F{6}Function ${name}%f'
    local print_function='print -P %F{4}Function ${name}%f'
    if [[ -n $optlist[v] ]]; then
        print_autoload_function='fn def "$name"'
        print_function='fn def "$name"'
        shift
    fi
    
    local desc
    for desc in $info; do
        case $desc in
            *'alias'*)
                print -P "%F{13}${desc#*alias for }%f"
            ;;
            *'autoload'*'function'*)
                ${=print_autoload_function}
            ;;
            *'function'*)
                ${=print_function}
            ;;
            *'not found'*)
                print -P "%F{9}${name} not found%f"
            ;;
            *'builtin'*)
                print -P "%F{4}shell builtin%f"
            ;;
            *'/'$name)
                print -P "%F{2}${desc#*$name is }%f"
            ;;
        esac
    done
}
