#!/bin/zsh

#  iff
#  Z-Function (74)
#
#  Created by Maxim Puchkov on 2020-06-25.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Evaluate and display the result of conditional expressions.
function iff() {(
    typeset expr
    typeset -i expr_value
    # Map int return codes to strings
    typeset -A labels
    if [[ -t 1 ]]; then
        labels=( [0]=$(green 'True') [1]=$(red 'False') )
    else
        labels=( [0]='True' [1]='False' )
    fi
    
    # Evaluate each argument
    for expr in $argv; do
        expr_cmd="[[ $expr ]]"
        eval '[[ '$expr' ]]; expr_value=$?;'
        if [[ -t 1 ]]; then
            notify -Pl -aC2 -- \
                "[[ $expr ]]" \
                "${labels[$expr_value]}"
        else
            print -- \
                "${(qqq)expr}" \
                "${labels[$expr_value]}"
        fi
    done
    
    return 0
)}
