#!/bin/zsh

#  man
#  Z-Function (1)
#
#  Created by Maxim Puchkov on 2020-04-25.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# colored-man-pages
function man() {
    function colored() {
        command env \
            LESS_TERMCAP_mb=$(printf "\e[1;36m") \
            LESS_TERMCAP_md=$(printf "\e[1;36m") \
            LESS_TERMCAP_me=$(printf "\e[0m") \
            LESS_TERMCAP_se=$(printf "\e[0m") \
            LESS_TERMCAP_so=$(printf "\e[1;7m") \
            LESS_TERMCAP_ue=$(printf "\e[0m") \
            LESS_TERMCAP_us=$(printf "\e[0;32m") \
            PAGER="${commands[less]:-$PAGER}" \
            _NROFF_U=1 \
            PATH="$HOME/bin:$PATH" \
                "$@"
    }
    colored $0 "$@"
}
