#!/bin/zsh

#  man
#  Z-Function (1)
#
#  Created by Maxim Puchkov on 2020-04-25.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# colored-man-pages
function man() {
    case ${1#-} in
        light) theme='light'
               shift         ;;
        dark)  shift         ;&
        *)     theme='dark'  ;;
    esac
    colored -t $theme $0 "$@"
}
