#!/bin/zsh

#  options_shift_distance
#  devx
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Return shift distance to exclude options
# from positional parameters.
function options_shift_distance() {
    local count=0
    while [[ $1 =~ "^-" ]] && [[ $1 != "--" ]]; do
        if [[ $2 =~ "^[^-]" ]]; then
            count=$(( $count + 1 ))
            shift
        fi
        count=$(( $count + 1 ))
        shift
    done
    echo $count
}
