#!/bin/zsh

#  pack
#  devx
#
#  Created by mpuchkov on 2020-03-04.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Create new empty subdirectory 'subdir'. Move all
# files in the parent directory 'dir' to 'dir/subdir'.
function pack() {
    typeset -A optlist=()
    get_options optlist 'e:Eo:On:N' "$@"
    shift $optlist[length]
    
    # -o
    local only=''
    if [[ -n $optlist[o] ]]; then
        only=( '-and -name '${(z)^optlist[o]} )
    fi
    # -e
    local except=''
    if [[ -n $optlist[e] ]]; then
        except=( '-and ! -name '${(z)^optlist[e]} )
    fi
    
    # Find files
    local dir="${1:-$PWD}"
    typeset -a files=(${(@f)"$( find "$dir" \
                                    ! -name '.*' \
                                    ! -flags hidden \
                                    -mindepth 1 \
                                    -maxdepth 1 \
                                    ${(z)only} \
                                    ${(z)except} )"}) 2&>/dev/null
    
    if [[ ${#files} -eq 0 ]]; then
        error 'No files.'
        return 1
    fi
    
    # Move files to the subdirectory
    local packname="$dir/${2:-Pack-${#files}}"
    if [[ -d "$packname" ]]; then
        error "Pack already exists: '$(red "$packname")'."
        return 1
    fi
    mkdir -p "$packname"
    mv "${(@f)files}" "$packname/"
    
    printf "Packed $(green '%s') files: $(green '%s').\n" ${#files} $packname
    return 0
}
