#!/bin/zsh

#  print-section
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# print-section - output formatted line of text
function print-section() {(
  autoload -Uz get
  get -L 1 -p 'opt_' -- $argv
  
  typeset escape_seq=${opt_e}
  typeset -i width=${opt_w:-$COLUMNS}
  typeset char=${opt_c:-'*'}
  typeset text
  if [[ ${+opt_t} -eq 1 ]]; then
    text="  ${opt_t}  "
  fi
  
  esc -n $=escape_seq
  builtin print -Pn -- "${(pr:$width::$char::$text:)}"
  esc -0
  return 0
)}
