#!/bin/zsh

#  print-0x
#  devx
#
#  Created by admin on 2020-03-01.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function print-0x() {(
    if [[ -z $argv ]]; then
        
    fi

    # Get ASCII input
    local ascii="$*"
#    if [[ -z "$ascii" ]]; then
#        read ascii
#    fi
    if [[ -z "$ascii" ]]; then
        error 'No ascii.'
        return 2
    fi
    
    
    
    # Convert to hexadecimal
    local hex=''
    hex=$( python -c '\
        ascii="'$ascii'"; \
        hex=bytes.hex(ascii.encode()); \
        print(hex);' )
#    hex=$( ascii2hex.py "$ascii" 2> /dev/null )
    
    if [[ -z $hex ]]; then
        return 1
    fi
    
    printf '%s' "$hex"
    return 0
)}
