#!/bin/zsh

#  print
#
#
#  Created by admin on 2020-08-05.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function print() {
#  autoload -Uz get
#  get -o Y -- $argv
  builtin print $argv
}
