#!/bin/zsh

#  printx
#  devx
#
#  Created by admin on 2020-03-01.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function printx() {
    # Get ASCII input
    local input="$*"
    if [[ -z "$input" ]]; then
        read input
    fi
    if [[ -z "$input" ]]; then
        error 'No input.'
        return 2
    fi
    
    # Convert to hexadecimal
    local hex=''
    hex=$( ascii2hex.py "$input" 2> /dev/null )
    
    if [[ -z $hex ]]; then
        return 1
    fi
    
    printf '%s\n' "$hex"
    return 0
}
