#!/bin/zsh

#  ref
#  Quick shell reload
#
#  Created by mpuchkov on 2020-04-21.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Reload autoloaded functions and shell files
function ref() {
    if [[ ! -f $REF_UPDATE ]]; then
        touch $REF_UPDATE
    fi
    
    # Check the list of shell source files
    typeset -a updated_source
    updated_source=($(< $ZTERM/etc/source.zsh))
    for f in $updated_source; do
        if [[ $f -nt $REF_UPDATE ]]; then
            builtin source $f
        fi
    done 2> /dev/null
    
    
    # Find updated functions
    typeset -a updated_functions
    updated_functions=($( find $zfunc -type f -mnewer $REF_UPDATE ))
    
    
    # Reload functions
    for f in ${updated_functions:t}; do
        builtin unfunction -m "${f}_*"
        builtin unfunction $f
        builtin autoload $f
    done 2> /dev/null
    
    
    
    touch $REF_UPDATE
    return 0
}


