#!/bin/zsh

#  section
#  Z-Function (8)
#
#  Created by Maxim Puchkov on 2020-04-29.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function section() {
    local manpage="$( man -w $1 )"
    
    local tmp=$( tempfile )
    trap  "rm -f $tmp" EXIT
    
    printf '%b\n' "$(tbl $manpage)" > $tmp
    title=$( grep -o -e '^\.TH.*$' -- "$tmp" )
    
    # awk "/^\.SH \"SIMPLE COMMANDS/,/PRECOMMAND MOD/"
    
    # | groff -mtty-char -Tascii -mandoc -c
    
    typeset -ag headers=(${(@f)"$(grep -e '^\.SH' -- "$tmp")"})
    name=${headers[1]}
    sections=(${headers:1})
    local n_sections=${#sections}
    echo $n_sections
    printf '%s\n' $headers
}
