#!/bin/zsh

#  shebang
#  zfc+ (99)
#
#  Created by Maxim Puchkov on 2020-07-13.
#  Copyright (c) 2020 Maxim Puchkov. All rights reserved.


# shebang
shebang () {
  local file=${1:=File}
  local project=${2:=Project}
  printf '#!%s\n\n%s\n\n\n%s\n' \
    '/bin/zsh' \
    "$(template copyright $file $project)" \
    "# $file"
}
