#!/bin/zsh

#  spectrum
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# <#Function description#>
function spectrum() {
    for code in {000..010}; do
        print -a -C2 -P -- \
        "$code: %{$FG[$code]%}$ZSH_SPECTRUM_TEXT%{$reset_color%}" \
        "$code: %{$BG[$code]%}$ZSH_SPECTRUM_TEXT%{$reset_color%}"
    done
}
