#!/bin/zsh

#  split_array
#  Z-Function (84)
#
#  Created by Maxim Puchkov on 2020-07-05.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Split array in two arrays 'left_split' and 'right_split' at
# next occurrence of 'str':
#   array(1..n)  ~>  left_split(1..i), right_split(i+1,n)
function split_array() {
  [[ ! -v sarr ]] && typeset -ag sarr=(L{1..3} '--' R{1..3})

  #    case $1 in
  #        ('.') shift ;;
  #        ('-') shift ;;
  #        ('+') shift ;;
  #    esac
  #
  typeset array_id=$1
  typeset split_str=$2

  typeset left_split_id=${3:-'left_split'}
  typeset right_split_id=${4:-'right_split'}



  #    typeset -ag $left_split_id $right_split_id

  print ${(P)array_id}
#    =${argv[(i)$split_str]}
  typeset -i split_index
  split_index=$(argn $split_str ${(P)array_id})
  print -- $split_index $split_str
  print ${${(P)array_id}[1,$split_index]}
} 
