#!/bin/zsh

#  tempfile
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-13.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Change directory and print its path.
function tempfile() {
    local ext="${1}"
    local subdirname='tempfiled'
    local prefix="${subdirname}/tempfile"
    
    if [[ ! -v TMPDIR ]]; then
        error "Environment variable '$(Bad TMPDIR)' is not set."
        return 2
    fi
    if [[ ! -r $TMPDIR ]]; then
        error "Access denied."
        return 1
    fi
    
    # Create 'tempfiled' subdirectory in 'TMPDIR'
    local subdir="${TMPDIR}/${subdirname}"
    if [[ ! -d "${subdir}" ]]; then
        mkdir -p -- "${subdir}"
    fi
    
    # Create temporary file
    local filepath=''
    if ! filepath=$( mktemp -t "${prefix}" 2> /dev/null ); then
        return $?
    fi
    
    # If specified, add file extension
    if [[ -n "${ext}" ]]; then
        if ( ! mv -- "${filepath}" "${filepath}.${ext}" ); then
            return 1
        fi
        filepath="${filepath}.${ext}"
    fi
    
    # Print path to the created file
    printf '%s' "${filepath}"
    return 0
}

