#!/bin/zsh

#  try
#  Z-Function
#
#  Created by mpuchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Try to evaluate boolean condition.
function try() {
    if [[ $# -eq 0 ]]; then
        error 'Missing arguments.'
        return 2
    fi
    
    if $( eval "[[ ${@} ]]" &> /dev/null ); then
        printf "-- $(green True) $(pass) --\n"
        return 0
    else
        printf "-- $(red False) $(fail) --\n";
        return 1
    fi
}
