#!/bin/zsh

#  usage
#  Z-Function (80)
#
#  Created by Maxim Puchkov on 2020-07-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Print command usage
function usage() {(
  setopt extendedglob
  case $1 in
    # No input
    '')
      error -1
      return
    ;;
    # Print an error message before usage
    '-e')
      typeset error_desc=$2
      shift 2
    ;;
  esac
  
  # Usage color and line prefix
  typeset -i color=6
  typeset prefix=${(%):-'\t %F{'${color}'}>%f'}
  
  # Append 'Usage' label to description
  typeset -a usage_desc=()
  usage_desc+=(${(%):-'%F{'${color}'}%U''Usage''%u%f:'})
  
  # Append arguments
  typeset -i i=1
  autoload -Uz get
  while [[ -n $1 ]]; do
    case $1 in
      (?[\!])
        usage_desc[$i]+=$(syntaxf " ${1%'!'}")
      ;;
      (+)
        [[ -z $2 ]] && error "Missing argument after ${1}"
        shift
        usage_desc[$i]+=$(syntaxf "\n\t   $1")
      ;;
      (-)
        [[ -z $2 ]] && error "Missing argument after ${1}"
        shift
        let i=$i+1
        usage_desc[$i]+=$(syntaxf "${prefix} $1")
      ;;
      (*)
        usage_desc[$i]+=$(syntaxf " $1")
      ;;
    esac
    shift
  done
  
  trap '{
    builtin print -- ${(@Fe)usage_desc}
  }' EXIT
  
  # Print error
#  if [[ -n $error_desc ]]; then
#    error -T +. "${error_desc}\n"${(@Fe)usage_desc}
#  else
#    builtin print -- ${(@Fe)usage_desc}
#  fi
  return $?
)}
