#!/bin/zsh

#  zbuiltins
#  devx
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Show enabled/disabled shell builtins
function zbuiltins() {
    local ON=$(green 'defined')
    local OFF=$(red 'undefined')
    local k v
    
    printf '%-20s%5s\n' "Builtin" "Status"
    for k v in ${(kv)builtins}; do
        local builtin_label=$k
        local value_label=$OFF
        if [[ $v == 'defined' ]]; then
            value_label=$ON;
        fi
        printf '%-20s%5s\n' "$builtin_label" "$value_label"
    done
}
