#!/bin/zsh

#  zfc_list
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-18.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


## list: list functions sorted by modification date ##
function zfc_list() (
    
    # Format the date
    function format_date() {
        printf '%s\n' "$( date -r $1 -j +'%b-%d-%Y %R' )"
    }
    
    #MARK: Preprocess files
    # Process files in the functions' directory
    local -a list=()
    local dir="$zfunc"
    for file in $dir/*; do
        local mod_date="$(stat -f '%m' $file)"
        list+=( "${(q)file##*'/'}" "${(q)mod_date}" )
    done
    
    # MARK: Options
    # Determine output format
    local show_lines=${#list:2}
    local sort_options='--key 2n'
    if [[ $# -gt 0 ]]; then
        local count=${1:-0}
        if [[ $count -gt 0 ]]; then
            sort_options='--key 2nr'
        else
            count=$(( $count * -1 ))
        fi
        show_lines=$count
    fi
    
    
    #MARK: Table Data
    # Table
    local -a table_header=()
    local table_div=''
    local div_length=0
    local -a table_body=()
    local div_length=''
    
    
    # Header
    local column1_header='FUNCTION'
    local column2_header='DATE MODIFIED'
    table_header=(
        "$( printf '%s\t\t%s' "$column1_header" "$column2_header" |
                expand -t 8 )"
    )
    
    # Divider line
    longest_row=(
        $( printf '%s %s\n' $list |
            awk '{print length, $1, $2}' |
            sort |
            tail -1 )
    )
    div_length=$(
        printf '%s %s\n' $longest_row[2] $(format_date $longest_row[3]) |
            column -t |
            wc -c
    )
    table_div=$(
        printf '%-*s\n' ${div_length} '' |
            tr ' ' '-'
    )
    
    # Table body
    local recent=$(
        printf '%s %s\n' $list |
            sort -k2n |
            tail -1 |
            awk '{print $1}'
    )
    table_body=$(
        printf '%s %s\n' ${(@)list} |
            sort ${(z)sort_options} |
            while read fn_name fn_mod_date; do
                local formatted_name="$(blue $fn_name)"
                local formatted_date="$(date -r $fn_mod_date -j +'%b-%d-%Y %R')"
                printf '%s %s' $formatted_name $formatted_date

                if [[ "$fn_name" == "$recent" ]]; then
                    printf '\t (%s)' "$(green 'most recent')"
                fi
                printf '\n'
            done |
        column -t |
        head -n $show_lines
    )
    
    
    # Print the table
    printf '%s\n' "$table_header"
    printf '%s\n' "$table_div"
    printf '%s\n'   "$table_body"
    return 0
)
