#!/bin/zsh

#  zopts
#  devx
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Show enabled/disabled options.
function zopts() {
    local ON=$(green 'on')
    local OFF=$(red 'off')
    local k v
    typeset -A list
    list=(${(kv)options})
    
    if [[ $# -gt 0 ]]; then
        local filter=$1
        case $filter in
            'on'|'off')   list=(${(kv)options[(R)$filter]}) ;;
        esac
    fi
    
    printf '%-20s%5s\n' "Option" "Status"
    for k v in ${(kv)list}; do
        local option_label=$k
        local value_label=$OFF
        if [[ $v == 'on' ]]; then
            value_label=$ON;
        fi
        printf '%-20s%5s\n' "$option_label" "$value_label"
    done
}
