#!/bin/zsh

#  ztrace
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Trace a command.
function ztrace() {
    trap "unfunction -m '${0}-*'" EXIT
    
    ## trace: print all commands ##
#    function ztrace-trace() {
#        print -P "%BTracing %U%F{5}${@}%f%u%b: %B%F{7}{%f%b"
#        local trace=$( setopt xtrace; $@ 2>&1; setopt noxtrace; )
#        print -P -- "%F{6}${trace:-<No output>}%f"
#        print -P "%B%F{7}}%f%b"
#        print -P "%BTrace of %U%F{5}${@}%f%u completed.%b"
#    }
    
    if [[ $# -eq 0 ]]; then
        return 1
    fi
    
    
    cmd=$1
    args=${@:2}
    print -P -- "%BTracing %F{4}%U${cmd}%u ${args}%f%b"
    # %B%F{7}{%f%b"
    print -P -- "%B%F{7}{%f%b"

    setopt xtrace
    typeset trace=$($@ 2>&1)
    setopt noxtrace
    printf '\e[36m'
    print -P -- "\e[36m%F{6}${trace:-%F\{1\}<No output>%f}%f"
    printf '\e[0m'

    print -P -- "%B%F{7}}%f%b"
#    print -P -- "%B%F{4}${exit_code}%f%b"

#    print -P -- "%B%U%F{4}${cmd}%u ${args}%f ($exit_code)%b"
#    print -- $cmd AAA $args
    
#    ztrace-trace "$@"
    return 0
}
