#!/bin/zsh

#  ztrace
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Trace a command.
function ztrace() {
    function __ztrace() {
        printf "\n$(magenta %s) $(bmagenta %s)...\n" 'Tracing' "${*}"
        setopt xtrace
        local trace=$( "$@" 2>&1 )
        printf "$(Info %s)\n" "${trace:-<No output>}"
        setopt noxtrace
        printf "$(magenta %s)\n\n" 'Trace complete.'
    }
    
    ## trace: print all commands
    function ztrace_trace() {
        echo $0
        print -P "%BTracing %U%F{5}${@}%f%u%b..."
    }
    trap "unfunction -m '${0}_*'" EXIT
    
    
    if [[ $# -eq 0 ]]; then
        return 1
    fi
    
    ztrace_trace "$@"
    return 0
}
