#!/bin/zsh

#  ztrace
#  Z-Function
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Trace a command.
function ztrace() {
    trap "unfunction -m '${0}_*'" EXIT
    
    ## trace: print all commands ##
    function ztrace_trace() {
        print -P "%BTracing %U%F{5}${@}%f%u%b: %B%F{7}{%f%b"
        local trace=$( setopt xtrace; $@ 2>&1; setopt noxtrace; )
        print -P -- "%F{6}${trace:-<No output>}%f"
        print -P "%B%F{7}}%f%b"
        print -P "%BTrace of %U%F{5}${@}%f%u completed.%b"
    }
    
    if [[ $# -eq 0 ]]; then
        return 1
    fi
    
    ztrace_trace "$@"
    return 0
}
