#!/bin/zsh

#  Config
#  
#
#  Created by mpuchkov on 2020-01-28.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


#MARK: - Printable
function printable() {
    SRC=$(basename $0)
    subcommand=$1
    case $subcommand in
        "")
            print "Printables: ${(kv)fprintable}"
            ;;
        "-h" | "--help" )
            printable_help
            ;;
        *)
            shift
            ${SRC}_${subcommand} $@
            if [ $? = 127 ]; then
                echo "Unknown command: $subcommand" >&2
            fi
            ;;
    esac
}

printable



#MARK: - Functions
function printable_unset() {
    fname="$1"
    fprintable[$fname]=""
    print ${(k)fprintable} > $cfg
    print "Disabled: $(r $fname)"
}

function printable_set() {
    fname="$1"
    fprintable[$fname]="on"
    print ${(k)fprintable} > $cfg
    print "Enabled: $(g $fname)"
}

function printable_cfg() {
    open -b com.apple.dt.Xcode $cfg
}
function printable_load() {
    while read -d ' ' fname; do
        fprintable[$fname]="on"
    done < $cfg
}

function printable_help() {
    echo "Usage: $SRC set|unset <function>"
}



#aaa() { if [[ $1 =~ "y[es]" ]]; then echo 'y'; fi }

function _test() { $(_test1); $(_test2); $(_test3) }
function _test1() {
    confirm
    echo "Test 1 confirmed"
}
function _test2() {
    ( confirm )
    echo "Test 2 ( confirmed )"
}
function _test3() {
    $( confirm )
    echo "Test 3 \$( confirmed )"
}



#MARK: - Data Init
typeset -A -x fprintable

cfg="$fp/config/.$SRC.cfg"
touch $cfg
printable_load

alias fpr='() { printable $*; }';
