# User-specific zsh environment for interactive
# and non-interactive shells.
#
# Created on March 29, 2020.


# Z-Shell directory
export ZTERM="/usr/local/Terminal"
export ZDOTDIR="$ZTERM/zsh"


# Hash directories
hash -d zterm=$ZTERM
hash -d zdot=$ZDOTDIR
hash -d bin=/usr/local/bin


# Z-Shell files
export ZSHENV="$HOME/.zshenv"
export ZPROFILE="$ZDOTDIR/.zprofile"
export ZSHRC="$ZDOTDIR/.zshrc"
export ZIO="$ZDOTDIR/.zio"
export ZALIAS="$ZDOTDIR/.zalias"
export ZEXPORT="$ZDOTDIR/.zexport"
export ZUTIL="$ZDOTDIR/.zutil"
export ZNET="$ZDOTDIR/.znetwork"
export ZMISC="$ZDOTDIR/.zmisc"
export ZCOMP="$ZDOTDIR/.zcomp"
export ZTEST="$ZDOTDIR/.ztest"
