# User-specific zsh environment for interactive
# and non-interactive shells.
#
# Created on March 29, 2020.


export ZSHENV="$HOME/.zshenv"
#export PYTHONENV="$HOME/.pythonenv"

#MARK: - Z-Shell Files
export ZTERM="/usr/local/Terminal"
export ZDOTDIR="$ZTERM/zsh"

export ZPROFILE="$ZDOTDIR/.zprofile"
export ZSHRC="$ZDOTDIR/.zshrc"
export ZIO="$ZDOTDIR/.zio"
export ZALIAS="$ZDOTDIR/.zalias"
export ZEXPORT="$ZDOTDIR/.zexport"
export ZUTIL="$ZDOTDIR/.zutil"
export ZNET="$ZDOTDIR/.znetwork"
export ZMISC="$ZDOTDIR/.zmisc"
export ZCOMP="$ZDOTDIR/.zcomp"
export ZTEST="$ZDOTDIR/.ztest"




#MARK: - Hashed Directories
# zsh
hash -d zterm=$ZTERM
hash -d zdot=$ZDOTDIR
hash -d zsh=$ZDOTDIR

hash -d bin=/usr/local/bin
hash -d var=~zterm/var
# zsh subdirectories
hash -d zs=~zdot/site-functions
hash -d zf=~zdot/functions
hash -d zc=~zdot/completions
# Documents
hash -d docs=~/Documents
hash -d dev=~/Developer
hash -d saved=~/Documents/Saved\ Files
# Library
hash -d scripts=~/Library/Scripts
hash -d iCloud=~/Library/Mobile\ Documents/com~apple~CloudDocs
hash -d Access=~iCloud/Access
hash -d sfu=~iCloud/SFU

hash -d sfu1=~sfu/01-Fall-2016
hash -d sfu2=~sfu/02-Spring-2017
hash -d sfu3=~sfu/03-Summer-2017
hash -d sfu4=~sfu/04-Fall-2017
hash -d sfu5=~sfu/05-Spring-2018
hash -d sfu6=~sfu/06-Summer-2018
hash -d sfu7=~sfu/07-Fall-2018
hash -d sfu8=~sfu/08-Spring-2019
hash -d sfu9=~sfu/09-Fall-2019
hash -d sfu10=~sfu/10-Spring-2020
