#!/bin/zsh

#  ???.zsh
#  Generated by mkzsh at 08:11pm.
#
#  Created by mpuchkov/506:20 on April 06, 2021.
#  ~/private/zsh/lib/???.zsh



#???: timeinfo <file>
function timeinfo() {
  stat -t '%Y-%b-%d at %l:%M:%S %p' -f 'Modified:%t%Sm' $@
}

#???: sedd <sed_cmds>
function sedd() {
  if [[ ! -v SED_FILE ]]; then
    print -z 'export SED_FILE='
    error -1 -m 'parameter is not set: ${SED_FILE}'
  fi
  SED_CMDS="$*"
  if [[ -z "$SED_CMDS" ]]; then
    error -1 -m 'missing sed commands'
  fi
  SED_ARGS=( -E -n -e "$SED_CMDS" "$SED_FILE" )
  command sed $SED_ARGS
}


#???: get_file_header:
#   Read file comments from file (until first non-comment line).
#   Store resulting lines in 'file_header' array. Empty lines are included.
function get_file_header() {
  local file=$1
  if [[ ! -r $file ]]; then
    error -1 -m 'cannot read file: ${file}.'
  fi
  typeset -g -a file_header
  file_header=( "${(@f)$(command sed -E -n -e '/^[[:blank:]]*([#]|$)/p' -e '/^[^#]/{q;}' <$file)}" )
  return 0
}


#???: list-functions-except <prefix>
# List functions except ...
function list-functions-except() {
  local -a except=( '+' '-' '_' 'prompt_' 'instant_' )
  print -nrC1 -oi -m '[^+-_]*' -- ${(k)functions}
}
