#!/bin/zsh

#  hooks.zsh
#  Generated by mkzsh at 11:47am.
#
#  Created by mpuchkov/506:20 on April 07, 2021.
#  ~/private/zsh/lib/hooks.zsh


# To add a preexec hook function:
#   `add-zsh-hook preexec <function>`


# Briefly announce executed command.
function announce-short() {
  say ${2[(w)1]:t} &!
}

# Announce typed command.
function announce() {
  say $1 &!
}
