#!/bin/zsh

#  iterm2.zsh
#  Generated by mkzsh at 03:28pm.
#
#  Created by mpuchkov/506:20 on April 07, 2021.
#  ~/private/zsh/lib/iterm2.zsh


# Docs: https://iterm2.com/python-api/
export ITERM2_APP_SUPPORT="$HOME/Library/Application Support/iTerm2"
export ITERM2_SHARED="/usr/local/share/iterm2"



###  Functions  ###
# iterm2-edit: edit iTerm scripts in Xcode.
function iterm2_edit {
  local -a files=()
  local iterm_scripts_dir="$HOME/Library/Application Support/iTerm2/Scripts"
  local name
  for name; do
    file="$iterm_scripts_dir/${${name:t}%.py}.py"
    files+="$file"
  done
  command open -a Xcode -- $files
}


function iterm2_annotate {
  printf '\e]1337;AddAnnotation=%i|%s\a' "${(c)#*}" "$*"
}

function iterm2_profile {
  if [[ -n "$*" ]]; then
    printf '\e]1337;SetProfile=%s\a' "$*"
  else
    printf 'Current Profile: %s\n' "$ITERM_PROFILE"
  fi
}


#TODO: [not implemented]
function iterm2_profconfig {
  local config="$ZDOTDIR/etc/profiles/$ITERM_PROFILE.zsh"
  echo $config
  [[ -e $config ]] && echo 1
}




##  Other functions  ##
function iterm2_notify {
  printf '\e]9;%s\a' "$*"
}
function iterm2_bounce {
  printf '\e]1337;RequestAttention=yes\a'
}
function iterm2_badge {
  printf '\e]1337;SetBadgeFormat=%s\a' "$(echo "$@" | command base64)"
}





# Completion
compdef '_arguments "*:*:( $HOME/Library/Application\ Support/iTerm2/Scripts/*.py(:t) )"' it2run





###  Aliases  ###
alias it2dynamic='open -a Xcode $ITERM2_SHARED/Dynamic Profiles/*'
alias it2scripts='open -a Xcode $ITERM2_APP_SUPPORT/iTerm2/Scripts/*'






# Run
alias 2r='it2run'
alias 2f='it2run call_function'
alias 2x='$ITERM2_SHARED/bin/it2xcrun'

# Profiles
alias 2p='iterm2_profile'
alias 2l='iterm2_profile Light'
alias 2d='iterm2_profile Dark'

# Profile and size
alias it2w='print -- "$ITERM_PROFILE (${COLUMNS}x${LINES})"'

# Python
alias it2py="\"$ITERM2_APP_SUPPORT/iterm2env/versions/3.8.6/bin/python3\""
