#!/bin/zsh

#  list.zsh
#  Generated by mkzsh at 11:45am.
#
#  Created by mpuchkov/506:20 on April 07, 2021.
#  ~/private/zsh/lib/list.zsh



###  Zsh Statistics  ###
function list-zsh-parameter-counts() {
  local -a params=( ${(s.+p:.)$(zmodload -lF zsh/parameter)} )
  local param
  local -A result
  for param in $params; do
    result[$param]="${(P)#param}"
  done
  print -nr -aC2 -- ${(kv)result} | command sort -k1d
}


function list-zsh-options() {
  typeset -a enabled_options disabled_options
  enabled_options=( $(print -nr -aC2 ${(kv)options} | sort -k1 | grep -w -F 'on') )
  disabled_options=( $(print -nr -aC2 ${(kv)options} | sort -k1 | grep -w -F 'off') )
  print -P -nr -aC2 -- '%F{1}'${^disabled_options}'%f' '%F{2}'${^enabled_options}'%f'
}
