#!/bin/zsh

#  misc.zsh
#  Generated by mkzsh at 07:18pm.
#
#  Created by mpuchkov/506:20 on April 06, 2021.
#  ~/private/zsh/lib/misc.zsh


# ls 
if [[ "$(tput colors)" -gt 8 ]]; then
  export LSCOLORS="GxFxcxdxbxegedabagacah"
else
  export LSCOLORS="Exfxcxdxbxegedabagacad"
fi
export LS_COLWIDTHS="8:3:3:0:6:8:4:0"
