#!/bin/zsh

#  error
#  devx
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Raise runtime function error:
#   error [-c exit_code] description
function error() {
    # Exit code.
    typeset -A opts
    get_options_v2 opts 'c:C' "$@"
    local _exitcode=${opts[c]:-1}
    shift $opts[length]
    
    # Error title and description.
    local _title="$( b_red 'Error.' )"
    local _desc="${@:-no message.}"
    
    # Capitalize first letter and add trailing period.
    _desc="${(C)_desc[1]}${${_desc:1}}"
    if [[ ! "${(q)_desc}" =~ $'\\n' ]] &&
        [[ ! "${(q)_desc}" =~ '^.*\.$' ]]; then
        _desc="${_desc}."
    fi
    
    # Print error and return.
    printf '%s %s\n' "$_title" "$_desc" >&2
    return _exitcode
}
