#!/bin/zsh

#  Shell
#
#
#  Created by mpuchkov on 2020-01-30.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function or() {
    local case1=$( echo $1 )
    local case2=$( echo ${2:Q} )
    gr $case1
    gr $case2
    if [[ -n "$case1" ]]; then
        echo $case1
    else
        echo $case2
    fi;
}
