#!/bin/zsh

#  printb
#  Z-Function (24)
#
#  Created by Maxim Puchkov on 2020-05-06.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function printb() {
    # Get hexadecimal input
    local input="$*"
    if [[ -z "$input" ]]; then
        read input
    fi
    if [[ -z "$input" ]]; then
        error 'No input.'
        return 2
    fi
    if [[ $(( ${#input} % 2 )) -ne 0 ]]; then
        error 'Invalid input length.'
        return 1
    fi
    
    # Convert to ASCII
    local ascii=''
    ascii=$( decode-hex.py "$input" 2>/dev/null )
    if [[ -z $ascii ]]; then
        return 1
    fi
    
    printf '%s' "$ascii"
    return 0
}
