#!/bin/zsh

#  writex
#  devx
#
#  Created by admin on 2020-03-01.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function writex() {
    # Check syntax.
    SYNTAX=(writex filepath text'*')
    case $# in
        0) serror 'filepath' "$SYNTAX"  ;;
        1) serror 'text'     "$SYNTAX"  ;;
    esac
    
    # Arguments.
    local dir=$1
    shift
    local input="$*"
    if [[ ${#input} -eq 0 ]]; then
        read input
    fi
    
    # Write input as hexadecimal string.
    write_bytes $dir "$input"
}
