#!/bin/zsh

#  semantic-history
#  Terminal
#
#  Created by Maxim Puchkov on 2020-04-17.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Path to the file
typeset filepath=$1
print $@ >/tmp/filepath

# If filepath contains extra characters
# try to delete last character until path
# refers to a readable file
until [[ -r $filepath ]]; do
  filepath=${filepath:0:-1}
done

# Open regular files in GUI editor
if [[ -f $filepath ]]; then
  /usr/local/bin/gui-edit $filepath
else
  open $filepath
fi

# Check exit code
typeset exit_code=$?
if [[ $exit_code -ne 0 ]]; then
  typeset title="Error (${exit_code})"
  typeset subtitle="${0:t}"
  typeset message="Cannot open '${filepath}'"
  osascript ~zterm/Tools/notify "$message" "$title" "$subtitle"
fi
return 0
