#!/bin/zsh

#  error
#
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Raise runtime error:
#   error description
function error() {
    # Error title and description.
    local _title="%F{9}Error%f."
    _desc="${(j:\n       :)@:-no message.}"
    # Capitalize first letter of the description
    # and add a trailing period.
    _desc="${(C)_desc[1]}${${_desc:1}}"
    if  [[ ! "${(q)_desc}" =~ '\n' ]] &&
        [[ ! "${(q)_desc}" =~ '^.*\.$' ]]; then
        _desc="${_desc}."
    fi
    # Print error and return.
    print -P "$_title $_desc" >&2
    return 1
}
