#!/bin/zsh

#  error
#
#
#  Created by admin on 2020-03-02.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


# Raise runtime error:
#   error description
function error() {
    # Error exit code.
    typeset -i10 exit_code=1
    if [[ $1 =~ '-[0-9]+' ]]; then
        exit_code=${1#-}
        shift
    fi
    
    # Return after this function exits.
    trap "return $exit_code" EXIT
    
    # Error title and description.
    typeset error_title error_desc
    error_title="%F{9}Error%f."
    error_desc="${(j:\n       :)@:-no message.}"
    
    # Capitalize first letter of the description
    # and add a trailing period.
    error_desc="${(C)error_desc[1]}${${error_desc:1}}"
    if  [[ ! "${(q)error_desc}" =~ '\n' ]] &&
        [[ ! "${(q)error_desc}" =~ '^.*\.$' ]]; then
        error_desc="${error_desc}."
    fi
    
    # Print error and return.
    print -P "$error_title $error_desc" >&2
    return $exit_code
}
