#!/bin/zsh

#  get_options
#  Z-Function
#
#  Created by admin on 2020-04-15.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.
 

# Read all command options and store in an array with
# the specified identifier.
function get_options() {
    local identifier=$1
    local optstring="$2"
    local arguments=(${@:3})
    
    local SYNTAX="$0 identifier optstring arguments*"
    syntax_check "$SYNTAX" ||
        return 1
    
    typeset -A result
    local opt=''
    local length=0
    while getopts "$optstring" opt $arguments; do
        if [[ $opt == '?' ]]; then
            length=$(( $length + 1 ))
            continue;
        fi
        if [[ -n $OPTARG ]]; then
            result[$opt]=$OPTARG
            length=$(( $length + 2 ))
        else
            result[$opt]='0'
            length=$(( $length + 1 ))
        fi
    done 2>/dev/null
    
    local arg_list=(${(z)arguments})
    result[length]=$length
    result[command_arguments]=${(qq)${arg_list:$length}:-''}
    
    typeset -Ag $identifier
    set -A $identifier ${(kv)result}
    return 0
}
