#!/bin/zsh

#  czsh
#  devx
#
#  Created by admin on 2020-03-11.
#  Copyright © 2020 Maxim Puchkov. All rights reserved.


function czsh() {
    env -i HOME="$HOME" bash -l -c 'bash'
#    export CLEAN_SHELL_ENV='set'
#    unset CLEAN_SHELL_ENV
}
